### ISSUE TITLE
Issues with tracker

### ISSUE THREAD

**Issue by yashoswalyo** [djinnalexio/eye-on-cursor#1]
[Screencast from 2024-05-29 19-59-08.webm](https://github.com/djinnalexio/eye-on-cursor/assets/42431299/2f3c5b6e-f28b-47b5-a388-d3b485136808)

- The tracker doesn not show up on widow menu
- Click effect is only working on desktop

Session: `Gnome 46 Wayland`

**Comment by yashoswalyo** [comment]
### Can you add click effect like this

https://github.com/djinnalexio/eye-on-cursor/assets/42431299/0364ec92-4aaf-41ab-bfbc-0b9d728eabb0

**Comment by djinnalexio** [comment]
> * The tracker doesn't show up on window menu

I'll see what I can do. Do you know if it was an issue in the old extension?

> * Click effect is only working on desktop

That's one of the known issues listed in the README. Basically, on Wayland, events are routed differently than on x11, and mouse clicks that happen in a window only happen in that window. **Eye and Mouse Extended** only used `Atspi` to listen to mouse clicks, which doesn't work at all on Wayland. That's the root of [this issue](https://github.com/alexeylovchikov/eye-extended-shell-extension/issues/17#issue-1908217087). That's why on Wayland, this extension resorts to listening with `globe.stage` instead, with its caveat that only clicks in the Shell (background, panel, etc.) are registered. 

> * Can you add click effect like this
 
Reimplementing the ripple animation is possible. I'll try to make it part of the changes for the next update.

**Comment by djinnalexio** [comment]
> Is there absolutely no way to get clicks from windows in Wayland now?

I searched and asked around and it's part of the drawbacks that is just accepted when it comes to Wayland. I don't think there's a way for GNOME extensions to circumvent those restrictions.

**Comment by djinnalexio** [comment]
https://github.com/djinnalexio/eye-on-cursor/releases/tag/v1.1.0

Update published. Points 1 and 3 have been taken care of.

The click on Wayland issue doesn't seem to be addressable here at the moment so I'll be putting it aside.
