### ISSUE TITLE
Issues with usage of extension "top bar organizer" 

### ISSUE THREAD

**Issue by Zeratoxx** [djinnalexio/eye-on-cursor#2]
# Issues with usage of extension "top bar organizer"

## Intro

Hi!

I love your extension so far!

## Issue

Now, there is an extension with the name "top bar organizer" that enables users to reorder the items in the top bar. Every time an item gets added to the top bar, the organizer registers it. The issue is at the name of the item: the organizer seems to match the reorder by name; but eye-on-cursor create a unique name every time - which effectively makes any setting in the organizer obsolete.

## Images

Here are some Screenshots for example:

---

Ideal setup
> ![image](https://github.com/user-attachments/assets/b9faacdb-75cb-4dce-a7aa-80972c1f8310)

---

After de- and reactivating the extension "eye-on-cursor"
> ![image](https://github.com/user-attachments/assets/6749e083-13f2-4e47-a687-efca8e248883)

---

## Proposal for solution

My proposal for a solution would be to use a predefined counter identifier. It is possible to increase the number of eyes, so just use this setting and count upwards for the identifiers - first eye index 0, second eye index 1, so on and so forth

**Comment by djinnalexio** [comment]
> I love your extension so far!

Hi there! Thanks! 

The issue has been addressed in version [1.2.1](https://github.com/djinnalexio/eye-on-cursor/releases/tag/v1.2.1) which should be validated soon if not already.  So you can just wait for the auto-update.

The reason it isn't part of v1.2.0 is that I just missed the issue until now. Thanks for the detailed report and proposed solution; they helped to deal with it quickly. The eyes needed to have non-duplicate IDs in order to be able to have multiple which is why I jumped to using `Random`. But turns out just using the counting already there does the job. They should now show as `eye-on-cursor-0`, `eye-on-cursor-1`, etc. I tested it with **Top Bar Organizer** and it now behaves as expected.

Also, thanks for bringing up **Top Bar Organizer**. I wanted to be able to control the placement of individual eyes instead of moving the group but I couldn't make it work. This extension basically gives me the feature I wanted!

![Screenshot from 2024-08-02 21-53-02](https://github.com/user-attachments/assets/c1a78c84-69ac-4924-b7da-e5686a8a3c36)

**Comment by Zeratoxx** [comment]
@djinnalexio thank you very much :D

Also, I'm happy that my input helped you in so many ways 😁
